version: '3.5'

networks:
  internal:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.0.0/24

services:
  nginx:
    hostname: nginx
    build:
      context: ./nginx
      dockerfile: ./dev.Dockerfile
    networks:
      internal:
        ipv4_address: 10.0.0.2
    ports:
      - 80:80
    volumes:
      - ./nginx/dev.nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/dev.conf.d:/etc/nginx/conf.d
      - ./nginx/conf.extra.d:/etc/nginx/conf.extra.d
    restart: unless-stopped

  backend:
    hostname: backend
    build:
      context: ./backend
      dockerfile: ./dev.Dockerfile
    env_file: ./backend/.env
    networks:
      internal:
        ipv4_address: 10.0.0.10
    ports:
      - 9000:3000
    volumes:
      - ./backend:/app
    restart: unless-stopped

  database:
    hostname: database
    build:
      context: ./database
      dockerfile: ./dev.Dockerfile
    env_file: ./database/.env
    networks:
      internal:
        ipv4_address: 10.0.0.20
    ports:
      - 5432:5432
    volumes:
      - ./docker/postgres/regio:/var/lib/postgresql/data/regio
    restart: unless-stopped

  pgadmin:
    hostname: pgadmin
    image: dpage/pgadmin4:${PGADMIN_VERSION:-4.5}
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-postgres@postgres}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-postgres}
    networks:
      internal:
        ipv4_address: 10.0.0.25
    volumes:
      - ./docker/pgadmin:/var/lib/pgadmin
    ports:
      - 5000:80
    restart: unless-stopped
