export const CURRENT_USER_REQUEST_LOGIN = 'CURRENT_USER_REQUEST_LOGIN'
export const CURRENT_USER_LOGIN = 'CURRENT_USER_LOGIN'
export const CURRENT_USER_LOGOUT = 'CURRENT_USER_LOGOUT'

export const BATCH_ADD = 'BATCH_ADD'
export const BATCH_ADD_BULK = 'BATCH_ADD_BULK'
export const BATCH_REMOVE = 'BATCH_REMOVE'
export const BATCH_UPDATE = 'BATCH_UPDATE'
export const BATCHES_ADD_PAGE = 'BATCHES_ADD_PAGE'
export const BATCHES_REMOVE_PAGE = 'BATCHES_REMOVE_PAGE'
export const BATCHES_REQUEST_PAGE = 'BATCHES_REQUEST_PAGE'
export const BATCHES_PURGE_PAGINATION = 'BATCHES_PURGE_PAGINATION'
export const BATCHES_UPDATE_COUNT = 'BATCHES_UPDATE_COUNT'

export const COUNTRY_ADD = 'COUNTRY_ADD'
export const COUNTRY_ADD_BULK = 'COUNTRY_ADD_BULK'

export const SESSIONYEAR_ADD = 'SESSIONYEAR_ADD'
export const SESSIONYEAR_ADD_BULK = 'SESSIONYEAR_ADD_BULK'
export const SESSIONYEAR_REMOVE = 'SESSIONYEAR_REMOVE'
export const SESSIONYEAR_UPDATE = 'SESSIONYEAR_UPDATE'
export const SESSIONYEARS_ADD_PAGE = 'SESSIONYEARS_ADD_PAGE'
export const SESSIONYEARS_REMOVE_PAGE = 'SESSIONYEARS_REMOVE_PAGE'
export const SESSIONYEARS_REQUEST_PAGE = 'SESSIONYEARS_REQUEST_PAGE'
export const SESSIONYEARS_PURGE_PAGINATION = 'SESSIONYEARS_PURGE_PAGINATION'
export const SESSIONYEARS_UPDATE_COUNT = 'SESSIONYEARS_UPDATE_COUNT'

export const TERM_ADD = 'TERM_ADD'
export const TERM_ADD_BULK = 'TERM_ADD_BULK'
export const TERM_REMOVE = 'TERM_REMOVE'
export const TERM_UPDATE = 'TERM_UPDATE'
export const TERMS_ADD_PAGE = 'TERMS_ADD_PAGE'
export const TERMS_REMOVE_PAGE = 'TERMS_REMOVE_PAGE'
export const TERMS_REQUEST_PAGE = 'TERMS_REQUEST_PAGE'
export const TERMS_PURGE_PAGINATION = 'TERMS_PURGE_PAGINATION'
export const TERMS_UPDATE_COUNT = 'TERMS_UPDATE_COUNT'

export const TERM_SECTIONS_SET = 'TERM_SECTIONS_SET'

export const TERM_ADD_BULK_BY_TEACHERID = 'TERM_ADD_BULK_BY_TEACHERID'

export const TERM_COURSES_SET = 'TERM_COURSES_SET'
export const TERMCOURSE_ADD = 'TERMCOURSE_ADD'
export const TERMCOURSE_UPDATE = 'TERMCOURSE_UPDATE'
export const TERMCOURSES_SET_BY_COURSEID = 'TERMCOURSES_SET_BY_COURSEID'
export const TERMCOURSETEACHERS_SET_BY_TERM = 'TERMCOURSETEACHERS_SET_BY_TERM'

export const COURSE_ADD = 'COURSE_ADD'
export const COURSE_ADD_BULK = 'COURSE_ADD_BULK'
export const COURSE_REMOVE = 'COURSE_REMOVE'
export const COURSE_UPDATE = 'COURSE_UPDATE'
export const COURSES_ADD_PAGE = 'COURSES_ADD_PAGE'
export const COURSES_REMOVE_PAGE = 'COURSES_REMOVE_PAGE'
export const COURSES_REQUEST_PAGE = 'COURSES_REQUEST_PAGE'
export const COURSES_PURGE_PAGINATION = 'COURSES_PURGE_PAGINATION'
export const COURSES_UPDATE_COUNT = 'COURSES_UPDATE_COUNT'

export const COURSES_ADD_BULK_FOR_TEACHER_TERM =
  'COURSES_ADD_BULK_FOR_TEACHER_TERM'

export const STUDENT_ADD = 'STUDENT_ADD'
export const STUDENT_ADD_BULK = 'STUDENT_ADD_BULK'
export const STUDENT_REMOVE = 'STUDENT_REMOVE'
export const STUDENT_UPDATE = 'STUDENT_UPDATE'
export const STUDENTS_ADD_PAGE = 'STUDENTS_ADD_PAGE'
export const STUDENTS_REMOVE_PAGE = 'STUDENTS_REMOVE_PAGE'
export const STUDENTS_REQUEST_PAGE = 'STUDENTS_REQUEST_PAGE'
export const STUDENTS_PURGE_PAGINATION = 'STUDENTS_PURGE_PAGINATION'
export const STUDENTS_UPDATE_COUNT = 'STUDENTS_UPDATE_COUNT'

export const STUDENT_ADVISER_SET = 'STUDENT_ADVISER_SET'

export const FEEDBACKSTATEMENT_BULK_ADD = 'FEEDBACKSTATEMENT_BULK_ADD'

export const STUDENTFEEDBACK_ADD_BULK = 'STUDENTFEEDBACK_ADD_BULK'

export const ENROLLMENT_ADD_BY_STUDENT_TERM_COURSE =
  'ENROLLMENT_ADD_BY_STUDENT_TERM_COURSE'
export const ENROLLMENT_ADD_BULK_BY_STUDENTID = 'ENROLLMENT_ADD_BULK_STUDENT'
export const ENROLLMENTS_APPROVE_BY_STUDENTID_TERMID =
  'ENROLLMENTS_APPROVE_BY_STUDENTID_TERMID'
export const ENROLLMENT_ADD_BULK_BY_TERM_COURSE =
  'ENROLLMENT_ADD_BULK_BY_TERM_COURSE'

export const RESEARCH_ADD_BY_TERM_COURSE = 'RESEARCH_ADD_BY_TERM_COURSE'
export const RESEARCH_ADD_BULK_BY_TERM_COURSE =
  'RESEARCH_ADD_BULK_BY_TERM_COURSE'

export const TEACHER_ADD = 'TEACHER_ADD'
export const TEACHER_ADD_BULK = 'TEACHER_ADD_BULK'
export const TEACHER_REMOVE = 'TEACHER_REMOVE'
export const TEACHER_UPDATE = 'TEACHER_UPDATE'
export const TEACHERS_ADD_PAGE = 'TEACHERS_ADD_PAGE'
export const TEACHERS_REMOVE_PAGE = 'TEACHERS_REMOVE_PAGE'
export const TEACHERS_REQUEST_PAGE = 'TEACHERS_REQUEST_PAGE'
export const TEACHERS_PURGE_PAGINATION = 'TEACHERS_PURGE_PAGINATION'
export const TEACHERS_UPDATE_COUNT = 'TEACHERS_UPDATE_COUNT'

export const ATTENDANCE_SET_BULK = 'ATTENDANCE_SET_BULK'
export const ATTENDANCE_SET = 'ATTENDANCE_SET'
export const ATTENDANCE_ADD_FOR_STUDENT_BY_TERM_COURSE =
  'ATTENDANCE_ADD_FOR_STUDENT_BY_TERM_COURSE'

export const MARKS_CLASSTEST_ADD_BULK_BY_STUDENT_TERM_COURSE =
  'MARKS_CLASSTEST_ADD_BULK_BY_STUDENT_TERM_COURSE'
export const MARKS_CLASSTEST_ADD_BULK_BY_TEACHER_TERM_COURSE =
  'MARKS_CLASSTEST_ADD_BULK_BY_TEACHER_TERM_COURSE'
export const MARKS_CLASSTEST_ADD_BULK_BY_TERM_COURSE =
  'MARKS_CLASSTEST_ADD_BULK_BY_TERM_COURSE'

export const MARKS_THEORY_ADD_BY_STUDENT_TERM_COURSE =
  'MARKS_THEORY_ADD_BY_STUDENT_TERM_COURSE'
export const MARKS_THEORY_ADD_BULK_BY_TEACHER_TERM_COURSE =
  'MARKS_THEORY_ADD_BULK_BY_TEACHER_TERM_COURSE'
export const MARKS_THEORY_ADD_BULK_BY_TERM_COURSE =
  'MARKS_THEORY_ADD_BULK_BY_TERM_COURSE'

export const MARKS_SESSIONAL_ADD_BY_STUDENT_TERM_COURSE =
  'MARKS_SESSIONAL_ADD_BY_STUDENT_TERM_COURSE'
export const MARKS_SESSIONAL_ADD_BULK_BY_TEACHER_TERM_COURSE =
  'MARKS_SESSIONAL_ADD_BULK_BY_TEACHER_TERM_COURSE'
export const MARKS_SESSIONAL_ADD_BULK_BY_TERM_COURSE =
  'MARKS_SESSIONAL_ADD_BULK_BY_TERM_COURSE'

export const MARKS_RESEARCH_ADD_BY_STUDENT_TERM_COURSE =
  'MARKS_RESEARCH_ADD_BY_STUDENT_TERM_COURSE'
export const MARKS_RESEARCH_ADD_BULK_BY_TEACHER_TERM_COURSE =
  'MARKS_RESEARCH_ADD_BULK_BY_TEACHER_TERM_COURSE'
export const MARKS_RESEARCH_ADD_BULK_BY_TERM_COURSE =
  'MARKS_RESEARCH_ADD_BULK_BY_TERM_COURSE'

export const ROUTINE_SLOTS_SET_ALL = 'ROUTINE_SLOTS_SET_ALL'
export const ROUTINES_ADD_BULK_BY_TERM = 'ROUTINES_ADD_BULK_BY_TERM'
export const WEEKPLANS_ADD_BULK_BY_TERM = 'WEEKPLANS_ADD_BULK_BY_TERM'
